configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/cloud-api-sdks%2Fcourt-listener-sdk-a1a9c13c1e7e3dd6b7f09514d1b5ba9eb19dbc8f0f9e4512b9dfc8b0baa8f42b.yml
openapi_spec_hash: dce67e5045872c0bdece09680e36ff8c
config_hash: d214ed762eda5d670d36be42e281016b
